# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0002_auto_20180530_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='doc',
            field=models.FileField(default='Doc/None/No-doc.pdf', upload_to='Docs/'),
        ),
    ]
